cloudutil/AutoSpotting

README.md
SETUP.md

This was my first time doing anything with Go so I'm absolutely open to any suggestions or changes to the setup recommendations there.

Add a setup page documenting steps to build and deploy your own binaries for the tool

---

cloudformation/stacks/AutoSpotting/template.json

The IAM role used by the lambda function needed to be updated in order
to get the ASG tags. It currently did not have it, which resulted in:
```
region.go:248: Failed to describe AutoScaling tags in us-east-1
AccessDenied: User:
arn:aws:sts::308824460317:assumed-role/AutoSpotting-LambdaExecutionRole-17GHN91Z6W9OE/AutoSpotting-LambdaFunction-V9LHZ91FKJK4
is not authorized to perform: autoscaling:DescribeTags
```
Solves: https://github.com/cristim/autospotting/issues/49

cloudformation: add autoscaling:DescribeTags right to template

---

core/autoscaling.go
core/autoscaling_test.go
core/instance.go
core/region.go
core/spot_instance_request.go

A little heavy handed - there is probably a better design, but this is a 'future proof' approach as it abstracts direct access to the map and puts the lock primitives in place.
Meant to fix #72

Uses a RWMutex to lock access to the instances catalog

---

core/launch_configuration.go
core/launch_configuration_test.go

This fixes #75, and adds a bunch of tests for the function that copies block device mappings.

Fix copying of block device mappings

---

core/autoscaling.go
core/autoscaling_test.go
core/instance_test.go
core/mock_test.go
core/spot_instance_request.go
core/spot_instance_request_test.go
core/spot_price_test.go

- Improvement test Pull Request
Should help with:
* https://github.com/cristim/autospotting/issues/41
* https://github.com/cristim/autospotting/issues/7
Most of the methods have been covered by this PR - roughly 65-70% is covered now.
Some methods have been modified to be easier to test (return of values, etc), some have been merged when possible, and some have been removed when not used, please refer to commit/commit's message for more details.
Other bigger methods however are not yet covered by this PR, I believe they might need to be modified/split/simplified to have a better testing/understanding/reading of them. Those are:
* [process](https://github.com/cristim/autospotting/blob/master/core/autoscaling.go#L171)
* [havingReadyToAttachSpotInstance](https://github.com/cristim/autospottin …

Test autoscaling

---

.travis.yml
Makefile

This ensures the code fails build verification in case it fails to pass go vet and go fmt. 
It also creates a few additional make targets called from TravisCI so that the Travis config file can be simplified and all the installation of dependencies and build logic is in the Makefile.

Run fmt and vet from TravisCI, build cleanups

---

START.md
terraform/autospotting/lambda.tf

Wasn't able to get this module working using the included terraform code due to error:
```
Handler 'handler' missing on module 'handler': plugin: symbol handler not found in plugin lambda
```
Digging into the code and comparing to the Cloudformation definition, I could see it is actually defined as "Handle" rather than "handle".  Fixing this allowed it to work.  Also saw reference to "handle" in the documentation so have also tweaked that.

Handler case fix

---

START.md

"rate(1 minutes)" is invalid and isn't accepted by the API.  Should be "rate(1 minute)"

fix typo in terraform example

---

core/launch_configuration.go
core/launch_configuration_test.go

Per discussion in #48, we need SecurityGroupId support for non-VPC. This flips between SecurityGroups and SecurityGroupId based off of "sg-", which while not perfect, is a good midterm solution
Confirmed it works in our scenario.

Handle #48 in short-term by using appropriate securitygroup form

---

core/autoscaling.go
core/autoscaling_test.go
core/mock_test.go
core/region.go
core/spot_instance_request_test.go

This is a WIP, it needs test updates as the tests currently panic now, at least on Go 1.8 (though running the local version itself is much smoother)
* Fixes #98 by adding paging for instances. I can confirm cause of that for us was having too many instances listed and not finding the spot nodes in the list.
Also, it covers two additional scenarios that also caused leaked and failed nodes in my testing:
* Like Grace Period, we also should not be attempting to add nodes still in pending state - instead, we should wait for next round, similar to grace period. This covers scenario where the pending->running takes longer than grace period timeout.
* Even if we do try to attach, we should still not try to detach if that fails. There's still a defer case for when at max …

Instance Paging and Pending Node Attach Scenarios - covers #98

---

core/autoscaling.go
core/instance.go
core/instance_test.go
core/launch_configuration.go
core/launch_configuration_test.go
core/region.go

- Bug fix
- Include EBS surcharging in price calculation. 
- Turn on EBS optimization if it is free. ( Implements #88 )
- Fix bug where launch config has EBS enabled but Autospotting selects an instance which does not have the capability. ( Fixes #115 )
```text
```

In progress: Enable EBS pricing and automatically turn on if free

---

.travis.yml

Update TravisCI builds to the latest golang version, 1.9

Use Go 1.9 in TravisCI

---

core/region.go

This should hopefully fix #126, but needs to be confirmed by someone who
can afford to run such expensive instances :-)
to it.
1. [x] (N/A) Functionality not applicable to all users should be configurable.
1. [x] (N/A) Configurations should be exposed through Lambda function environment …

Propagate GPU count into the instance type information

---

cloudformation/stacks/AutoSpotting/template.json
core/autoscaling.go
core/autoscaling_test.go
core/mock_test.go
terraform/autospotting/autospotting-policy.json

Fixes #138
to it.
[CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.json)
and …

use TerminateInstanceInAutoScalingGroup instead of Detach

---

expiration.go

Was going through the code and found that though `isExpired` was been called with `ExpirationDate`, the method was still referring to `main.ExpirationDate`. 
It's a small change but more intuitive while going through the code.
to it. …

minor refactor: Refer to argument in isExpired 

---

START.md
autospotting.go
cloudformation/stacks/AutoSpotting/template.json
core/config.go
core/region.go
core/region_test.go
terraform/autospotting.tf
terraform/autospotting/lambda.tf
terraform/autospotting/variables.tf
terraform/variables.tf

This patch adds a new global option called on_demand_price_multiplier that is primarily intended to be used to support EC2 volume discounts. The option could also be used to set your set your bid price to be higher than the on demand price to reduce the chances that your spot instances will be terminated.
Note: There are currently no tests associated with this change. I started to write some tests for region.determineInstanceTypeInformation(), however ec2instancesinfo.regionPrices is not exposed publicly. Before I started sending you other pull requests to make these changes I first wanted to see if you would accept a patch like this or if you would like this feature to be implemented in a different manner.

add new global option on_demand_price_multiplier to support volume discounts

---

core/autoscaling.go
core/autoscaling_test.go

Prevent actively destruction of the last remaining instance. This is not intended to be an ultimate solution for #104 but should prevent harm by itself.
Open for any suggestion as I am new to golang.

prevent termination of last instance, should improve #104

---

cloudformation/stacks/AutoSpotting/template.json

Cloudformation didn't have option to set `AllowedInstanceTypes` from lambda. 
Autospotting code supports overriding allowed instance type in spot, but through lambda it's not possible with the current cloudformation template. 
Cloudformation template needs to set environment variable `ALLOWED_INSTANCE_TYPES`  in lambda to override AllowInstanceTypes in autospotting config.

Added environment variable in cloudformation to configure lambda to override allowed instance types.

---

START.md

To facilitate devlopment on the project, documenting a way to have a
better output & understanding of the way it works seemed important.
Despite the fact that those options aren't available via
cloudformation/terraform it is now more obvious how to use it.
Closes https://github.com/cristim/autospotting/issues/109

doc: add information for enabling debug option

---

START.md
autospotting.go
cloudformation/stacks/AutoSpotting/template.json
core/autoscaling.go
core/autoscaling_test.go
core/config.go
terraform/autospotting.tf
terraform/autospotting/lambda.tf
terraform/autospotting/variables.tf
terraform/variables.tf

- Feature Pull Request, implements #119.
Added configurable policy to place bids at a multiple of spot instance price or at on-demand price. Also added dynamic tag to enable this feature for an auto-scaling group.
Code review process:
The issue should be tagged with 'review wanted' label before the checklist below
is satisfied from the perspective of the PR author and the code is ready to be
peer-reviewed.
to it.
1. [x] No issues are reported when running `make …

Added SpotInstance Percentage Multiplier with dynamic tags

---

Makefile

Due to the one-line in the Makefile, the exit was done on a subprocess
instead of the Makefile itself. Removing the grouping by a standard
if/then fixed this issue.
Closes https://github.com/cristim/autospotting/issues/188
On a fresh golang:1.9 container:
```bash
root@78bee51a11d0:/go/src/autospotting# make check_deps
Error: dependency 'golint' is absent
Makefile:28: recipe for target 'check_deps' failed
make: *** [check_deps] Error 1
root@78bee51a11d0:/go/src/autospotting#  go get -u github.com/golang/lint/golint
root@78bee51a11d0:/go/src/autospotting# make check_deps
all dependencies satisifed: wget git golint go
```
to it.
1. …

Makefile: check_deps exits properly on failure

---

autospotting.go
cloudformation/stacks/AutoSpotting/template.json
core/autoscaling.go
core/autoscaling_test.go
core/config.go
core/instance.go
core/instance_test.go

This adds a new `disallowed-instance-types` option that can be set as a command line flag, environment variable, or ASG tag. It supports a comma separated list of instance types as well as globs. I needed this for https://github.com/cristim/autospotting/issues/190. While I don't think this closes that issue, it does offer a work around.
to it.
1. [ ] Functionality not applicable to all …

Add a disallowed-instance-types option

---

core/region.go
core/region_test.go

https://github.com/cristim/autospotting/issues/199
to it.
[CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.json)
and …

Allow larger number of autoscaling group names

---

START.md
autospotting.go
cloudformation/stacks/AutoSpotting/parameters.yaml
core/autoscaling.go
core/autoscaling_test.go
core/instance.go
terraform/autospotting.tf
terraform/autospotting/lambda.tf
terraform/autospotting/variables.tf
terraform/variables.tf

(All of the above)
As reported [here](https://github.com/cristim/autospotting/issues/198) and [there](https://github.com/cristim/autospotting/pull/196#pullrequestreview-87979399). There were couple elements that could have been improved with the option.
This PR add/fixes:
* add terraform option & doc
* ensure no empty elements are within the list
* review logic, to give priority to ASG tags rather than global configuration
Closes: https://github.com/cristim/autospotting/issues/198
to it.
1. [x] All new …

disallowed-type: improve logic & add option in terraform/doc

---

TECHNICAL_DETAILS.md

To gain a bit in visility about the evolution and/or support of existing
options and/or features 2 tables have been added to make it easier to
see.
Result looks like [this](https://github.com/cristim/autospotting/blob/hr-174/TECHNICAL_DETAILS.md#summary-of-supported-features--options).
Closes: https://github.com/cristim/autospotting/issues/174
to it.
1. [x] Functionality not …

doc: add table of supported feature/options tables

---

terraform/autospotting/variables.tf

#214 broke terraform deployments due to this missing variable.
to it.
[CloudFormation](https://github.com/cristim/autospotting/blob/maste …

Add missing autospotting_spot_product_description variable

---

Makefile

Replace lambda path in template_build_{build}.json to match build number.
Now you should change path to specific build manually because it defaults to most recent build.
to it. …

Replace lambda path in template_build_{build}.json

---

core/region.go
core/region_test.go

fixes #225 
to it.
[CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.json)
and …

fixes #225

---

core/autoscaling.go
core/autoscaling_test.go
core/launch_configuration.go
core/launch_configuration_test.go
core/mock_test.go
terraform/autospotting/autospotting-policy.json

- Bugfix Pull Request for https://github.com/cristim/autospotting/issues/48.
This PR is one way to fix https://github.com/cristim/autospotting/issues/48.  (The first commit is just an unrelated cleanup commit however.)
We want to attach the correct SecurityGroups to newly created spot instances. For that we just reuse the SecurityGroup attached to the instances in the auto scaling group but it turns out that those Security Groups can either be mentioned by name (in the classic EC2 or the DefaultVPC case) or by id (in the Lunix/UNIX (VPC) case).
In order to make the handling of these different cases easier we try to use IDs in all cases. If a SecurityGroup string starts with "sg-" we assume it's an idea already and use it as is. Otherwise we search for the string as a group name using the …

Use Security Group IDs in all cases

---

core/autoscaling.go
core/autoscaling_test.go

To know from which LaunchConfiguration the spot instances were started
with, it seemed interesting to add such tag as default.
Closes: https://github.com/cristim/autospotting/issues/165
to it.
variables which are also passed as parameters …

autoscaling: add LC Name tag by default

---

core/autoscaling.go
core/autoscaling_test.go

When detaching an instance from a Autoscaling Group autospotting just starts the detach and then immediately terminate the instance, this will make some requests during this time fail:
To reproduce: create an ALB, put 2 instances with a simple webserver for example  [http-echo](https://github.com/hashicorp/http-echo) and launch 2 new instances, result will be some missing requests when autospotting swap the on-demand instance to  spot-instances
```
Sun Apr 8 14:12:23 CEST 2018 version4: ip-10-0-62-37
Sun Apr 8 14:12:23 CEST 2018<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
Sun Apr 8 14:12:23 CEST 2018<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white"> …
```

Add a sleep to let detachment initialize properly before terminating

---

FAQ.md
README.md
START.md
TECHNICAL_DETAILS.md
autospotting.go
cloudformation/stacks/AutoSpotting/template.json
core/config.go
core/main.go
core/main_test.go
core/region.go
core/region_test.go
terraform/autospotting.tf
terraform/autospotting/lambda.tf
terraform/autospotting/lambda/main.tf
terraform/autospotting/lambda/variables.tf
terraform/autospotting/variables.tf
terraform/variables.tf

Implements #242.
Implements #242, see that for more details.
to it.
[CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.json) …

Add support for opt-out mode

---

START.md
cloudformation/stacks/AutoSpotting/template.yaml

The tags for autospotting_min_on_demand_percentage and autospotting_min_on_demand_number were incorrectly specified in the documentation as autospotting_on_demand_percentage and autospotting_on_demand_number. This PR fixes that.
[The code where the actual tags are specified is here.](https://github.com/cristim/autospotting/blob/69ed6177f6d06324e3b962080807977751cb2f21/core/autoscaling.go)
to it.
1. [ ] No issues are reported when running …

Documentation fix for Demand Tags Fixes #253

---

Makefile

Fixes the "Can not build on OSX" issue raised on #260.
The culprit is the wc command provided by OSX.
Also, makes the Makefile a bit more harmonic in its use of ```ifeq```/```ifneq```.
```
$ gofmt -l -s ./core/config.go ./core/instance.go ./core/launch_configuration.go ./core/connections.go ./core/region.go ./core/region_test.go ./core/instance_test.go ./core/launch_configuration_test.go ./core/connections_test.go ./core/spot_price_test.go ./core/autoscaling_test.go ./core/spot_price.go ./core/mock_test.go ./core/autoscaling.go ./core/main.go ./core/main_test.go ./autospotting.go | wc -l
```
yields
```
0
```
which is then compared to ```0``` using
```
ifneq ($(shell gofmt -l -s $(GOFILES) | wc -l), 0)
````
Which ends up in the if clause in any case.
Gnu coreutils, …

Fix #260: Handle different wc behaviour of OS X and coreutils

---

Makefile

If `go get` is running on a machine where package existing in GOPATH, then it will not update the package. To update it flag `-u` should be used.
https://rakyll.org/go-tool-flags/

Add "-u" flag to "go get" calls

---

core/instance.go

The current behaviour is when an instance is still within grace period isReadyToAttach returns false with no log message, as it is the default behaviour of this function. 
The intended log message for an instance still within the grace period is in fact displayed when the grace period has already passed and isReadyToAttach returns true. 
Corrected the log message which is displayed when instance up time has passed the grace period. 
Added an additional message to log when an instance is still within grace period, and return false. as per the previous behaviour.
1. [] The contribution fixes a single existing github issue, and it is linked
to it.  …

Correct log messages in isReadyToAttach

---

core/autoscaling.go
core/autoscaling_test.go

Fixes #290 
to it.
1. [x] Functionality not applicable to all users should be configurable.
1. [x] Configurations should be exposed through Lambda function environment
[CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.yaml)
and …

Check ASG min OD rules before launching new spot instance

---

core/region.go
core/region_test.go

#246 - Using filter tags with wildcard does not work
Add support for using regular expressions to filter instances at the value level for any ASG. The expressions are bounded so a plain string is treated as a basic equality test while a well formed expression needs no bounds, which could be a nuisance on the command line. Expressions are case-sensitive
Rationale is to support broader filtering capabilities and narrowly to service a users needs.
Fixes #246 
`make full-test` failing on mainline `master`. Skipping as a requirement.

Using filter tags with wildcard does not work #246

---

Makefile

go-lint package location changed from github to golang.org
This is to fix this error during builds : package github.com/golang/lint/golint: code in directory /go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
Golint seems to have updated their package location.

Makefile Golint package location broken

---

autospotting.go
cloudformation/stacks/AutoSpotting/template.yaml
core/mock_test.go
core/spot_termination.go
core/spot_termination_test.go

When a spot instance termination event is triggered, the lambda will get the
region and the instance id from the event data. With this data, it will detach
that instance.
The template now contains another CloudWatch EventRule to trigger the lambda 
when a spot instance termination notification is received.
The lambda detaches the instance when it receives the termination notification from
CloudWatch.
Note: The new EventRule is only present in the cloudformation template. 
to it.
1. [ ] All new functionality is covered by automated test cases so the …

Detach instance when spot termination notification is received

---

cloudformation/stacks/AutoSpotting/template.yaml

We need permission for CloudWatch Events to Publish to SNS Topic and
permission for SNS Topic to invoke main Lambda.
Fix #319
1. [X ] The contribution fixes a single existing github issue, and it is linked
to it. …

Detach instance when spot termination notification is received - missing permissions

---

autospotting.go

Lambda can be triggered by CloudWatch EventRule (scheduling) or by a SNS
Topic.
In the last case we need to extract the original message, published by
the Termination Notification CloudWatch EventRule, and pass it to
GetInstanceIDDueForTermination.
Fix for #322 
1. [ X] The contribution fixes a single existing github issue, and it is linked
to it.
1. [ X] No issues are reported when running `make full-test`.
1. [ ] Configurations should be exposed …

Detach instance when spot termination notification is received - event is not from CloudWatch but from SNS #322

---

core/autoscaling.go

Currently.
A spotted instance is launched.
Before the next autospot execution the ondemand instance that autospot
next execution should have replaced is terminated.
The launched spot instance, that is no more necessary, is not terminated.
The idea is:
once we found a spot instance launched for an ASG, we first check if the
ASG still need it.
If not we terminate the spot instance.
Beacuse we cannot know if the ASG will need it in the future and after
how much time.
To test:
create an ASG with min=max=desired=1
wait until autospot launch a spot for that ASG
set min=desired=0
look at next autospot execution log for a line like:
```
2019/02/15 13:33:24 autoscaling.go:366: Spot instance i-0fa844e5c281023a0 is not need anymore by ASG ecs-s-d-AutoScalingGroup-DLZ9BYSWB9V4 …
```

Terminate unused spot instances #321

---

autospotting.go
cloudformation/stacks/AutoSpotting/template.yaml
core/config.go
core/mock_test.go
core/spot_termination.go
core/spot_termination_test.go

Idea:
At the moment, when a termination notification message is received,
we are only supporting detach as action on the terminating spot instance.
Detaching an instance do not trigger Lifecycle Hook (LH).
This patch add a new option "termination_notification_action" with
relative CloudFormation parameter "TerminationNotificationAction" that
support the options:
```
detach
current behaviour - no LH Triggered
terminate
new behaviour - spot instance is terminated without decrementing
desired capacity, so that ASG spawn a new instance (same as detach) - LH
Triggered.
auto
new behaviour - if ASG has a LH for Terminate Lifecycle
Transition, action is "terminate", if not action is detach.
```
The option is global for all ASG.
But using "auto", behaviour is based on the …

Termination Notification Configurable Action

---

cloudformation/stacks/AutoSpotting/template.yaml
core/mock_test.go
core/spot_termination.go
core/spot_termination_test.go

In some situation (described in detail in #327), a detaching near termination
spot instance can be used to replace an ondemand one.
This fix delete the Tag 'launched-for-asg' after successfully detaching
a spot instance.
Fixes #327
1. [X] The contribution fixes a single existing github issue, and it is linked
to it.
1. [X] All new functionality is covered by automated test cases so the overall …

Delete Tag 'launched-for-asg' when detaching a spot instance

---

cloudformation/stacks/AutoSpotting/regional_stack_lambda.py
cloudformation/stacks/AutoSpotting/regional_template.yaml
cloudformation/stacks/AutoSpotting/template.yaml

* regional_template.yaml/template.yaml.
As role are cross region, there is no need to create a LambdaExecutionRole
and relative LambdaPolicy in all regions. We can just create one in the main
template's region and pass it's arn as parameter to the lambda that create the regional ones.
* regional_template.yaml.
Now that we have a lambda in the same region of the event,
there is no need to use sns at all, regional CW events can send directly
to regional lambda.
To avoid change in autospotting.go's code, CW event is "encapsulated"
as an SNS message.
* template.yaml/regional_stack_lambda.py.
To test all this i needed to add a new template parameter splitting
the LambdaZipPath one in LambdaS3BucketPrefix and LambdaZipName.
LambdaS3BucketPrefix is the bucket prefix from which are loaded all …

Template simplifications on Fix/termination signal

---

core/instance.go
core/instance_test.go

* Fixes https://github.com/cristim/autospotting/issues/285
* Add appropriate EC2 tag depending on if we are using launch config or
template
Fixes https://github.com/cristim/autospotting/issues/285, which would prevent usage of launch templates, due to specifying both the ID and name at the same time.
to it.
1. [x] Functionality not applicable to all users should be configurable.
1. [x] …

Add support for environments using Launch Templates

---

cloudformation/stacks/AutoSpotting/template.yaml
core/instance.go
core/instance_test.go
core/mock_test.go

The RunInstances input needs to be cleaned from any attributes conflicting with Network interface definition coming from the group's LaunchTemplate.
I also tidied up the tests since in the real world LaunchTemplates can't be configured together with LaunchConfigurations on the same ASG.
This hopefully fixes #345 but needs to be tested and confirmed.
to it.
1. [N/A] Functionality not …

Support launch templates with network configuration

---

docker-compose.yaml

Have been playing with docker-compose for building the code to test, I notice that if you use `docker-compose up` then `FLAVOR` will always be `nightly` which causes the BINARY_LICENSE to be included however I'm not sure if this should be the correct behaviour as we could run `make travisci-docker` locally and `FLAVOR` will default to custom
Doing this will still default to `FLAVOR=nightly` if the environment variable is unset or empty, however you can now specify your own `FLAVOR` for docker-compose
to it.
1. [ ] All new functionality is covered by …

Allow flavor to be customised

---

Makefile

The `-i` option is not specified in POSIX `sed`. As such, different implementations handle it differently.
See https://unix.stackexchange.com/questions/92895/how-can-i-achieve-portability-with-sed-i-in-place-editing
Fixes #377
Bugfix Pull Request
Fixes `mark archive` on macOS by using POSIX-compliant `sed` invocation.
to it.
1. [x] No issues are reported …

Fix `make archive` on macOS

---

core/connections.go
core/region.go

I don't think these logs decrease the signal-to-noise ratio for everyday use, although others may disagree.
I'm happy to break this up into smaller PRs if that's desired, and I'm happy to remove anything from this PR that you think is worth keeping.
Fixes #382
Move some logs to debug.
In my tests, I'm seeing lines logged go from > 500 to < 100 for invocations where AutoSpotting doesn't terminate or launch any instances. 
to it.
1. [ ] All new …

Move some logs to debug

---

core/autoscaling_configuration.go
core/autoscaling_configuration_test.go
core/instance.go
core/instance_test.go

Fixes #380
Bugfix Pull Request
Bid at current spot price when spot_price_buffer_percentage is 0, instead of bidding at 10% above spot price.
See #380 for discussion.
to it.
1. [ ] Configurations should be exposed through …

Support spot price buffer percentage of 0

---

core/spot_termination.go
core/spot_termination_test.go

Fixes #387
Fix segfault when we get a spot instance termination warning and the instance in question does not belong to an autoscaling group.
to it.
1. [ ] Configurations should be exposed through …

Don't segfault when spot instance doesn't belong to ASG

---

autospotting.go
core/mock_test.go
core/spot_termination.go
core/spot_termination_test.go

This is a reworking of #363 against `master`. 
Since this fixes a fairly serious issues for those running AutoSpotting in multi-tenant environments, I think it makes sense to merge this first and then tackle remaining issues that are preventing #354 from being merged. 
Credit for original code goes to @cfarrend.
Fixes #362
Closes #363
Closes #390
to it.
test …

Ignore terminating spot instances that don't belong to AutoSpotting

---

Makefile

It's implied if you specify `--exit-code-from`, but if you don't pass it you get an annoying warning.
Bugfix Pull Request
Fixes this warning when calling `docker-compose`:
to it.
1. [ ] Configurations should be exposed …

Pass --abort-on-container-exit to docker-compose

---

core/autoscaling.go
core/autoscaling_test.go

It previously mutated the receiver, but did not return the loaded launchConfiguration.
This was pulled out of #354, with some additional error handling.
Pulling out a small part of the big event-based-instance-replacement work. This part seems fairly inconsequential, but need to start somewhere :) 
to it.
1. [ ] No issues are reported …

Make loadLaunchConfiguration return a launchConfiguration

---

.travis.yml
Makefile
docker-compose.yaml

These targets are pretty much generic and do not need to run in TravisCI. 
I specifically have a use case where I am running some of them in a different CI provider, so invoking `make travisci` is awkward. And who knows, maybe in the future we'll all be using GitHub actions 😉  
Rename the following make targets:
- `travisci-cover` -> `ci-cover`
- `travisci-checks` -> `ci-checks`
- `travisci` -> `ci`
- `travisci-docker` -> `ci-docker`
to it.
1. …

Rename travisci make targets to ci

---

core/main.go
core/main_test.go
core/spot_price_test.go

This change was pulled from #354.
I actually think TestMain needs to be rethought in light of issues like https://github.com/AutoSpotting/AutoSpotting/issues/358 (real code doesn't always initialize globals, so neither should tests), but punting on that until the larger changes from #354 are done. 
to it.
1. [ ] No issues are reported when running `make …

Move TestMain from spot_price_test.go to main_test.go

---

core/mock_test.go
core/region_test.go
core/spot_price.go
core/spot_price_test.go

This may help with #376.
Use `DescribeSpotPriceHistoryPages` instead of `DescribeSpotPriceHistory`.
to it.
variables which are …

Use paginated version of DescribeSpotPriceHistory

---

core/autoscaling_configuration.go
core/instance.go
core/instance_test.go

Previously, the amount of logs generated when replacing a large
number of on-demand instances could be overwhelming since info about
each candidate instance type was logged. Now, we still log when an
instance type matches, but now all the logs about every instance type
that does not match will be at debug level.
This change was begun in https://github.com/AutoSpotting/AutoSpotting/pull/354/files#diff-fa23d3c4fb090da3bc9f71371d6e1d95R446.
Reduce amount of logs generated when attempting to find compatible instance types.
to it.
1. [ ] The code is as simple as possible, readable …

Move logs about incompatible instance types to debug

---

Makefile

`ifeq` and similar Makefile constructs run _before_ target invocation.
This means that `go vet` and `gofmt` were being run when targets
like `make help` were run.
FWIW, I don't think the extra code added much over simply invoking
`go vet` and `gofmt`. Their output is already very good.
Don't run `go vet` and `go fmt` in every invocation of `make`.
to it.
test …

Remove incorrect Makefile conditionals

---

START.md
cloudformation/stacks/AutoSpotting/template.yaml
core/autoscaling.go
core/autoscaling_configuration.go
core/autoscaling_test.go
core/config.go
core/region.go

Currently when using a premium OS such as RHEL the on demand price of any instance is taken from the standard linux version of the instance type and as such doesn't take into account the extra fees paid for premium instances. Further to this the spot price is calculated using the spot product description which when entered as "Red Had Enterprise Linux" gives a spot price which may be greater than the on demand price for standard linux instances, especially on smaller instances and so does not replace the on demand instance as it thinks there are no savings to be made.
This change looks to address the issue above by allowing a premium value to be set, for example 0.06 for RHEL, so that this can be added to the on demand price for a standard linux OS to giving an …

Added spot premium

---

core/instance.go
core/instance_test.go

A bug fix for PR #423, currently when calculating the bid price for premium instances, using the aggressive policy, the premium is included when calculating the buffer and as such this adds on a buffer for the premium which should be fixed.
For example
A standard instance
ondemand price = 0.1
spot price = 0.05
premium = 0.0
buffer = 50%
would give a bid price of 0.075, which would be lower than the on demand price.
A premium instance
ondemand price = 0.16
spot price = 0.11
premium = 0.06
buffer = 50%
would give a bid price of 0.165, which would be higher than the on demand price.
A premium instance after this fix
ondemand price = 0.16
spot price = 0.11
premium = 0.06
buffer = 50%
would give a bid price of 0.135, which would be lower than the on demand price.
1. [x] I …

Update how bid price is calculated for premium instances

---

core/autoscaling_configuration.go
core/autoscaling_configuration_test.go

When an ASG has both "autospotting_min_on_demand_percentage" and
"autospotting_min_on_demand_number" tags, use whichever is the larger
number each time.  In other words, allow the static minimum number
of instances to override the percentage when the poolsize it small.
With this change in place, in the event an ASG has tags specifying both a static
number and a percentage for "minimum on-demand" instances, Autospotting will
use whichever is larger.
As a result, the static number can be used to enforce an absolute minimum which
will take precedence when the number of instances in the ASG is small.  But when
the ASG grows larger during higher traffic periods, the percentage will control the
minimum number of on-demand instances.  It allows for more aggressive spot use …

Use the larger of min-OD-instances and (min-OD-percent * current)

---

core/action.go

Sorry but with latest merge, in particular:
```
* terminateUnneededSpotInstance - no need to call
asg.terminateRandomSpotInstanceIfHavingEnough
```
i forgot to remove `total := tusi.target.totalInstances` that was only used by `asg.terminateRandomSpotInstanceIfHavingEnough`
1. [X ] I hereby allow the Copyright holder the rights to distribute this piece of
to it.
1. [ ] No issues are reported when running `make …

terminateUnneededSpotInstance - fix to total is unused

---

core/autoscaling.go
core/autoscaling_test.go
core/config.go
core/instance.go
core/main.go

As sometimes it's difficult to parse log output to find out which action have been taken by AutoSpotting schedule run, especially if you have many ASG, this PR add a final output after having processed all regions that show only if some action have been taken on an AutoScalingGroup (instance terminated, replaced or spot launched and so on)
Here an example output:
```
SC:2020-10-22T11:40:00 2020/10/22 11:41:12 main.go:74: ####### BEGIN FINAL RECAP #######
SC:2020-10-22T11:40:00 2020/10/22 11:41:12 main.go:77: eu-west-1 rmq-u-d-AutoScalingGroup-E0AA2BJJLA1I OnDemand instance i-02feae0a90d03651d replaced with spot instance i-04caa6efea8a30242
SC:2020-10-22T11:16:00 2020/10/22 11:16:40 main.go:77: eu-west-1 els-u-d-AutoScalingGroup-V4UV43APWMHZ Launched spot instance …
```

Add log output after having processed all regions that show actions taken by AS ScheduleRun

---

core/autoscaling.go
core/autoscaling_test.go
core/instance.go
core/launch_template.go
core/launch_template_test.go
core/mock_test.go

Fixes #430, where ephemeral volumes weren't being counted from the AMI used by a launch template when considering the acceptable instance types.
to it.
1. [x] Functionality not applicable to all users should be configurable.
1. [x] Configurations should be exposed through …

re #430: allows counting ephemeral volumes desired via AMI specified by ASG launch template (w/ version)

---

cloudformation/stacks/AutoSpotting/template.yaml

When trying to launch AutoSpotting in my AWS account I got the following errors during creation of regional stacks (StackSet disabled)
>
2020-11-11T10:22:53.462-03:00	Traceback (most recent call last):
2020-11-11T10:22:53.462-03:00	File "/var/lang/lib/python3.6/threading.py", line 916, in _bootstrap_inner
2020-11-11T10:22:53.462-03:00	self.run()
2020-11-11T10:22:53.462-03:00	File "/var/lang/lib/python3.6/threading.py", line 864, in run
2020-11-11T10:22:53.462-03:00	self._target(*self._args, **self._kwargs)
2020-11-11T10:22:53.462-03:00	File "/var/task/regional_stack_lambda.py", line 47, in create_stack
2020-11-11T10:22:53.462-03:00	'ParameterValue': role_arn,
2020-11-11T10:22:53.462-03:00	File "/var/runtime/botocore/client.py", line 316, in _api_call …

Add explicit bucket permissions for regional resources deployment

---

cloudformation/stacks/AutoSpotting/regional_template.yaml
cloudformation/stacks/AutoSpotting/template.yaml
core/main.go
core/spot_termination.go
core/spot_termination_test.go

Fixes #448 by handling [EC2 Rebalance Recommendation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/rebalance-recommendations.html#monitor-rebalance-recommendations) event in the same way a Spot Interruption event was already handled by AutoSpotting.
to it.
1. [x] …

Support for handling EC2 Rebalance Recommendation event

---

core/action.go
core/autoscaling.go
core/main.go
core/region.go
core/spot_termination.go

guidelines:
* all replacement of ondemand with spot should be handled by sqs
messages and for the same ASG be sequentially
* spot life "outside asg" should be as short as possible
* should be possible to run without using SQSQueue, but ONLY wihout using
event based replacement too (cron only, so that cannot run at the same time two AS execution)
* only one method, swapWithGroupMember, is used to do ondeamnd
replacement
AS = Autospotting
CW = CloudWatch
SQS = Sqs Queue
CRON = Cron Schedule
1) CW ondemand event:
send message to SQS
2) SQS ondemand event:
launch spot replcament - wait for spot running - replace with
swapWithGroupMember
3) CW spot event:
do nothing (it's' needed to avoid intercepting spot launch of point 1)
4) CRON need to launch spot to replace ondemand:
if SQS is enabled we …

Sqs workflow improvements

---

core/autoscaling.go
core/autoscaling_configuration.go
core/config.go
core/instance.go
core/instance_test.go
core/mock_test.go

As per https://aws.amazon.com/blogs/aws/new-ebs-volume-type-io2-more-iops-gib-higher-durability/ they have 100x Higher Durability and 10x More IOPS/GiB at the same cost. Similar awesomeness is available on GP3 as per https://aws.amazon.com/blogs/aws/new-amazon-ebs-gp3-volume-lets-you-provision-performance-separate-from-capacity-and-offers-20-lower-price/
What we have so far:
- Added configuration support with per-ASG tag-based overrides for the GP2 threshold
- Set default threshold value to 170GB, apparently that's the threshold where GP2 bandwidth overtakes the GP3, but for IOPS the threshold is at 1TB. This is configurable at the Lambda binary level but not yet exposed through CloudFormation/Terraform
- Add regional blacklist for the IO1->IO2 conversion for the …

Automatically upgrade EBS volumes of launched spot instances from GP2->GP3 and IO1->IO2 for lower cost and/or higher performance

---

CUSTOM_BUILDS.md

DockerHub now has case-sensitive URLs, thus the one in the docs was broken.
1. [ ✓] I hereby allow the Copyright holder the rights to distribute this piece of

dockerHub's URL structure is now case-sensitive.

---

core/config.go
core/main.go

Added a parameter disable_instance_rebalance_recommendation (default to
false) to disable handling of instance rebalance recommendation events.
Often that events are false positive, the spot instance is not
terminated and even if now we do not remove anymore the tag:
launched-for-asg
can happen that, if we detach instance, the rate at which AutoSpotting
cron event terminate unused spot (usually 5min) is greater than the rate at which AWS send IRR events
(usually IRR events are related to the instance type and not
specifically to the instance itself).
What happen is:
AWS send IRR, we deatch spot instance (without decreasing ASG)
ASG launch a new ondemand
if ondemand is in different AZ of the previous detached instance, AS
cannot use it, so launch a new spot
AWS send …

Parameter to disable handling of instance rebalance recommendation events

---

cloudformation/stacks/AutoSpotting/template.yaml

In https://github.com/AutoSpotting/AutoSpotting/pull/467 i forgot to add the relative template parameter and propagate it to the lambda.
1. [X ] I hereby allow the Copyright holder the rights to distribute this piece of
to it.
1. [ ] Configurations should be exposed through Lambda …

Fix to forgotten template parameter to disable IRR 

---

core/main.go

Before calling findUnattachedInstanceLaunchedForThisASG we need to
populate a.region.instances.instances calling r.scanInstances().
This is a fix to https://github.com/cloudutil/AutoSpotting/pull/468.
Before calling findUnattachedInstanceLaunchedForThisASG we need to
populate a.region.instances.instances calling r.scanInstances().
1. [ X] I hereby allow the Copyright holder the rights to distribute this piece of
to it.
test coverage doesn't …

fix to PR 468 (look if there is already a spot to use) - need to populate region instances

---

cloudformation/stacks/AutoSpotting/template.yaml
core/config.go
core/main.go

Someone reported instance replacements on groups tagged with spot-enabled=true even though the Lambda was configured with another tag.
Turns out the replacements were done by the billing Fargate task which ran without any filters and applied changes to groups tagged with the default tag spot-enabled=true
This commit adds a flag that disable any instance replacements and sets if on the Fargate task, in order to avoid undesired instance replacements
1. [ ] I hereby allow the Copyright holder the rights to distribute this piece of
to it. …

Add a flag for running in billing-only mode 

---

CUSTOM_BUILDS.md
Makefile
cloudformation/stacks/AutoSpotting/template.yaml

This makes AutoSpotting build and run as ARM binaries, which makes it slightly cheaper and faster at runtime, and also friendlier to my current local development setup. 
Intel binaries are still supported by the build process using the GOARCH environment variable, but the Infrastructure code will only deploy ARM infrastructure, which is not currently configurable.
Caveats:
- This will make the build process require a `docker buildx` setup on Intel hardware
- It will make it slower to build AutoSpotting on Intel-based hardware.
If you're interested to add support making the infrastructure code configurable as well, patches are always welcome. …

Switch Lambda and Fargate to arm64

---

core/instance_conversion.go

Fix to #479
In `createLaunchTemplateData` we need to first process the `ImageBlockDevices` and later process the LaunchTemplate/LaunchConfiguration, otherway we overwrite the LT/LC data BlockDevices VolumeSize with the image default one.
1. [X] I hereby allow the Copyright holder the rights to distribute this piece of
1. [X] The contribution fixes a single existing github issue, and it is linked
to it.
1. [ ] Functionality not …

fix to LaunchTemplate VolumeSize overwritten by Image
