- README.md
- SETUP.md
- core/instance.go
- core/launch_configuration.go
- core/spot_price.go
Trying to clean up some of the issues reported on [codeclimate](https://codeclimate.com/github/cristim/autospotting)
> Codeclimate fixes

- core/autoscaling.go
- core/raw_json_instance_data.go
- core/region.go
- core/spot_instance_request.go
- Add check for errors where it was missed
- Simplify checks for boolean variables
> Fix several linter issues

- core/launch_configuration_test.go
- Delete unneeded declaration
- Add new test for countLaunchConfigEphemeralVolumes() method
> Update for launch_configuration_test.go

- core/autoscaling.go
- core/spot_instance_request.go
- core/spot_instance_request_test.go
Would close https://github.com/cristim/autospotting/issues/45
> Add tests for spot_instance_request.go

- CUSTOM_BUILDS.md
A user noticed that the custom builds documentation was inaccurate and suggested some fixes.
Once at it, I also noticed some more and I did a few more improvements.
> Improve documentation of custom builds

- autospotting.go
- core/config.go
- core/connections.go
- core/connections_test.go
- core/instance.go
- core/instance_test.go
- core/main.go
- core/main_test.go
- core/mock_test.go
- core/spot_instance_request.go
> Test coverage increase

- autospotting.go
- core/autoscaling.go
- core/autoscaling_test.go
- core/config.go
- core/instance.go
- core/instance_test.go
- core/main.go
- core/mock_test.go
- core/region.go
- core/region_test.go
- core/spot_instance_request.go
- core/spot_instance_request_test.go
- core/spot_price_test.go
This implements a fix for #111, and should also fix #20
> Spot request tagging fixes

- Makefile
Run golint in `make full-test`, fixes #123.
> Perform golint checks

- core/instance.go
- core/instance_test.go
Fixes #126.
This should fix #126
> Also use GPU number for instance compatibility

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Fixes #122 
This resulted from #120, in which the code review took much longer than expected by the contributor. The contributor was towards the end frustrated that some requirements were not clear from the beginning and at the end the review was hastily passed through the rest of the process.
At the end, the contribution was still somewhat faulty (buggy per-group configuration overrides) and missing documentation so other users had a hard time making use of it.
> Add a code contribution checklist

- README.md
Add a list of companies using AutoSpotting
> Add a list of AutoSpotting users

- Makefile.lambda
- autospotting.go
Fix TravisCI build after latest Golang Lambda shim container updates
> Fix TravisCI builds

- Makefile
This fixes the broken TravisCI build.
> Forgot to git add the Makefile

- FAQ.md
FAQ.md: include info about ELB draining.
Fixes #150 
[ x ] The contribution fixes a single existing github issue, and it is linked
> FAQ.md: add ELB draining info

- FAQ.md
> Fixes typo in documentation(FAQ.md)

- cloudformation/stacks/AutoSpotting/template.json
Thank you for creating/supporting this project! 😄  This is the least I can do.
> Fix a couple minor typos in parameter description

- README.md
Add www.branch.io to the list of users in the README.md file
> Add branch to README.md

- README.md
Removing comma splices and minor changes to punctuation.
Cleaning many of the comma splices out of the Readme file.  In some cases just removed.  In other cases, split the thought into more than one sentence.
> Removing comma splices from Readme

- terraform/autospotting.tf
> Fix Terraform typo

- Makefile
As discussed in https://github.com/cristim/autospotting/pull/264
> Add make target to update dependencies

- core/instance.go
- core/instance_test.go
This was missing even if configured on the on-demand instances, we lost
it when changing the code to RunInstances
- Bugfix Pull Request, fixes #271 
Set the AssociatePublicIpAddress field when launching spot instances
This was reported to be missing by @atillamas on gitter. The code snippet that was doing it was dropped by mistake when changing the code to RunInstances.
to it.
1. [ ] Functionality not …
> Set the AssociatePublicIpAddress on spot instances

- Makefile
Added additional flags `-s -w` to minimize binary size. It goes down from 22MB to 13MB. A detailed description can be found here: https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/
I tried UPX as well in the past and from my experience sometimes it causes very strange crashes during runtime. Therefore, I would recommend doing it only if there is a clear requirement for a smaller size...
to it.
1. [x] No issues are reported …
> Add additional build flags

- CUSTOM_BUILDS.md
Fix unavailable build_local command
> Fix unavailable build_local command

- CHANGELOG.md
- FAQ.md
- START.md
- kubernetes/autospotting-cron.yaml.example
- Added the Kubernetes configuration example contributed by @sunnynew, thanks for this!
- Also updated the changelog
- FIx a few small markdownlint issues throughout the documentation.
to it.
variables which are also passed as …
> Update docs, add example for running as K8s cron job

- terraform/autospotting.tf
- terraform/autospotting/label.tf
- terraform/autospotting/lambda.tf
- terraform/autospotting/lambda/label.tf
- terraform/autospotting/lambda/main.tf
- terraform/autospotting/lambda/variables.tf
- terraform/autospotting/output.tf
- terraform/autospotting/variables.tf
- terraform/label.tf
- terraform/variables.tf
> Use dynamic names for terraform resources so the module can be reused

- CUSTOM_BUILDS.md
Updated the doco to package default or custom binaries for a lambda function
This is just for advanced users, but still, it is good to have it for clarity
> Updated the doco to package default or custom binaries for a lambda function

- .editorconfig
- CONTRIBUTING.md
- FAQ.md
- Makefile
- START.md
- TECHNICAL_DETAILS.md
- cloudformation/Makefile
- cloudformation/stacks/AutoSpotting/regional_stack_lambda.py
- cloudformation/stacks/AutoSpotting/regional_template.yaml
- cloudformation/stacks/AutoSpotting/template.yaml
This should fix #331, you can see more context there.
to it.
1. [N/A] All new functionality is covered by automated test cases so the overall
1. [N/A] Functionality not applicable to all users should be configurable.
1. [N/A] Configurations should be exposed through Lambda function environment
[CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.yaml) …
> Fix/termination signal handling, fixes #331

- Makefile
https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
Travis CI makes encrypted variables and data available only to pull
requests coming from the same repository. These are considered
trustworthy, as only members with write access to the repository can
send them.
to it.
1. [ ] Functionality not applicable to all users should be …
> Skip Coverall if token missing

- autospotting.go
This way we can pass to main lambda a cloudwatch event or an sns
that contain/forward a cloudwatch's one.
The code is even more clear to read and implement a better logic.
As we now extract region directly from CW event, even in case of an sns
message, there is no more need to parse sns arn using strings library.
In a successive PR TerminationEventRuleFunction in regional_template.yaml
can be modified to direclty send CW event (no more need to encapsulate
it in an SNS message).
to it.
1. [ ] All new functionality is covered by automated test cases so the …
> Rewrite main Handler method to parse sns and event

- TECHNICAL_DETAILS.md
Fix typo of 'lifecycle' in the document. Very small PR
to it.
[CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.yaml) …
> Fix typo in TECHNICAL_DETAILS.md

- go.mod
- go.sum
Accounts
Updates the AWS SDK to the latest versioned release. This allows for use of the new AWS feature: [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).
Code review process:
The issue should be tagged with 'review wanted' label before the checklist below
is satisfied from the perspective of the PR author and the code is ready to be
peer-reviewed.
The label should be set by a maintainer as soon as the review is requested on
Gitter and should only be cleared after the PR is merged.
-->
to it. …
> Updating AWS SDK to latest version

- CUSTOM_BUILDS.md
- Makefile
> Allow specifying GOOS and GOARCH

- Makefile
There are some bashisms in the Makefile that cause errors when using other shells.
Fixes #395 
to it.
1. [ ] Configurations should be exposed through …
> Use /bin/bash for shell

- core/autoscaling.go
- core/autoscaling_test.go
- core/instance.go
Split off from #354 with some small tweaks to get tests to pass.
to it. …
> Refactor instance.isProtectedFromTermination

- Makefile
This reverts commit cb9748f875db93d8c9f01fb12976a82e97027e80.
It broke the build in alpine, and I don't think it actually solved a real issue.
Reverts #396. 
Bugfix Pull Request
to it.
1. [ ] Configurations should be exposed …
> Revert "Use /bin/bash for shell"

- autospotting.go
This is a small refactoring pulled from #354.
to it. …
> Delete cfgData type

- core/mock_test.go
We never call DescribeSecurityGroups. If we did, we should probably call the paginated version instead.
to it.
variables …
> Delete DescribeSecurityGroups mock

- Makefile
Due to golang/go#24230, `gofmt` doesn't actually exit with an error code when it detects misformatted files. The recommended solution is to check if it wrote anything to stdout.
Fix the fact that the build doesn't actually fail when code is not properly formatted. This broke in #418. 
to it.
1. [ ] No issues are reported when running …
> Actually fail the build if gofmt fails

- core/autoscaling.go
With the current detach-then-attach behavior (if asg desiredCapacity != minSize), spot instances attachment might fail while the on-demand instance has been detached / terminated by AutoSpotting. This PR forces on-demand replacement to attach-then-detach in all cases, so an on-demand instance won't be replaced if spot attachment fails.
Fixes #428.
to it.
test …
> Force on-demand replacement to be attach-detach

- cloudformation/stacks/AutoSpotting/template.yaml
Removed duplicated key in the cloud formation template
> Removed duplicated type key

- core/main.go
before launching a new spot instance look if there is already a spot one
to use.
Can mitigate  problem described in
https://github.com/AutoSpotting/AutoSpotting/pull/467
1. [X ] I hereby allow the Copyright holder the rights to distribute this piece of
to it.
1. [ ] Configurations …
> when handling new ondemand event look if there is already a spot to use
